-- Initial CourseService schema.
-- Flyway is the source of truth for production database structure.

CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(120) NOT NULL,
    title VARCHAR(200) NOT NULL,
    short_description VARCHAR(500),
    description TEXT,
    difficulty VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    access_type VARCHAR(32) NOT NULL,
    enrollment_enabled BOOLEAN NOT NULL,
    cover_image_url VARCHAR(1000),
    estimated_minutes INTEGER,
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    published_at TIMESTAMP(6) WITH TIME ZONE,

    CONSTRAINT uk_courses_slug UNIQUE (slug),
    CONSTRAINT chk_courses_difficulty CHECK (difficulty IN ('BEGINNER', 'INTERMEDIATE', 'ADVANCED')),
    CONSTRAINT chk_courses_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    CONSTRAINT chk_courses_access_type CHECK (access_type IN ('PUBLIC', 'UNLISTED', 'PRIVATE'))
);

CREATE TABLE course_modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    order_index INTEGER NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT fk_course_modules_course_id
        FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT uk_course_modules_course_order UNIQUE (course_id, order_index)
);

CREATE INDEX idx_course_modules_course_id ON course_modules (course_id);

CREATE TABLE course_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    item_type VARCHAR(32) NOT NULL,
    statement TEXT,
    starter_code TEXT,
    language VARCHAR(50),
    order_index INTEGER NOT NULL,
    time_limit_ms INTEGER,
    memory_limit_mb INTEGER,
    output_limit_kb INTEGER,
    network_disabled BOOLEAN NOT NULL,
    read_only_fs BOOLEAN NOT NULL,
    comparison_mode VARCHAR(32) NOT NULL,
    normalize_line_endings BOOLEAN NOT NULL,
    trim_trailing_whitespaces BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT fk_course_items_module_id
        FOREIGN KEY (module_id) REFERENCES course_modules (id) ON DELETE CASCADE,
    CONSTRAINT uk_course_items_module_order UNIQUE (module_id, order_index),
    CONSTRAINT chk_course_items_item_type CHECK (item_type IN ('CODING', 'SQL', 'QUIZ', 'THEORY', 'FILE')),
    CONSTRAINT chk_course_items_comparison_mode CHECK (comparison_mode IN ('EXACT'))
);

CREATE INDEX idx_course_items_module_id ON course_items (module_id);

CREATE TABLE course_item_content_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL,
    block_type VARCHAR(32) NOT NULL,
    order_index INTEGER NOT NULL,
    title VARCHAR(200),
    text_content TEXT,
    url VARCHAR(1000),
    language VARCHAR(50),
    metadata_json TEXT,

    CONSTRAINT fk_course_item_content_blocks_item_id
        FOREIGN KEY (item_id) REFERENCES course_items (id) ON DELETE CASCADE,
    CONSTRAINT uk_course_item_content_blocks_item_order UNIQUE (item_id, order_index),
    CONSTRAINT chk_course_item_content_blocks_block_type CHECK (block_type IN ('TEXT', 'VIDEO', 'IMAGE', 'CODE', 'EMBED', 'FILE'))
);

CREATE INDEX idx_course_item_content_blocks_item_id ON course_item_content_blocks (item_id);

CREATE TABLE course_item_hints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL,
    order_index INTEGER NOT NULL,
    text TEXT NOT NULL,

    CONSTRAINT fk_course_item_hints_item_id
        FOREIGN KEY (item_id) REFERENCES course_items (id) ON DELETE CASCADE,
    CONSTRAINT uk_course_item_hints_item_order UNIQUE (item_id, order_index)
);

CREATE INDEX idx_course_item_hints_item_id ON course_item_hints (item_id);

CREATE TABLE course_item_test_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL,
    test_key VARCHAR(120) NOT NULL,
    order_index INTEGER NOT NULL,
    visibility VARCHAR(32) NOT NULL,
    input_data TEXT,
    expected_output TEXT,

    CONSTRAINT fk_course_item_test_cases_item_id
        FOREIGN KEY (item_id) REFERENCES course_items (id) ON DELETE CASCADE,
    CONSTRAINT uk_course_item_test_cases_item_key UNIQUE (item_id, test_key),
    CONSTRAINT uk_course_item_test_cases_item_order UNIQUE (item_id, order_index),
    CONSTRAINT chk_course_item_test_cases_visibility CHECK (visibility IN ('OPEN', 'HIDDEN'))
);

CREATE INDEX idx_course_item_test_cases_item_id ON course_item_test_cases (item_id);
CREATE INDEX idx_course_item_test_cases_visibility ON course_item_test_cases (visibility);

CREATE TABLE course_item_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL,
    order_index INTEGER NOT NULL,
    label VARCHAR(20),
    text TEXT NOT NULL,
    correct BOOLEAN NOT NULL,
    explanation TEXT,

    CONSTRAINT fk_course_item_options_item_id
        FOREIGN KEY (item_id) REFERENCES course_items (id) ON DELETE CASCADE,
    CONSTRAINT uk_course_item_options_item_order UNIQUE (item_id, order_index)
);

CREATE INDEX idx_course_item_options_item_id ON course_item_options (item_id);
